import test from "node:test";
import assert from "node:assert/strict";
import { compareAtsScores, cvDraftToScoringText, scoreHealthcareCV } from "../src/utils/atsScoring.js";

const nurse={skills:["Patient assessment","Medication administration","Clinical documentation"],verbs:["Delivered","Improved"]};
test("ATS score is deterministic and improves with supported evidence",()=>{const basic=scoreHealthcareCV({cvText:"email@test.com Experience Education Skills",roleConfig:nurse,licenceAuthority:"NMC"});const strong=scoreHealthcareCV({cvText:"email@test.com +44123456789 Experience Education Clinical Skills Certification NMC Patient assessment Medication administration Clinical documentation Delivered care to 20 patients per shift and Improved audit compliance by 15%.",jobDescription:"patient assessment medication administration clinical documentation",roleConfig:nurse,licenceAuthority:"NMC"});assert.equal(strong.score,scoreHealthcareCV({cvText:"email@test.com +44123456789 Experience Education Clinical Skills Certification NMC Patient assessment Medication administration Clinical documentation Delivered care to 20 patients per shift and Improved audit compliance by 15%.",jobDescription:"patient assessment medication administration clinical documentation",roleConfig:nurse,licenceAuthority:"NMC"}).score);assert.ok(strong.score>basic.score);assert.equal(strong.scores.credentialMatch,100)});
test("missing licence is reported as a critical transparent check",()=>{const report=scoreHealthcareCV({cvText:"Experience Education Skills",roleConfig:nurse,licenceAuthority:"DHA"});const licence=report.checks.find(x=>x.id==="licence");assert.equal(licence.points,0);assert.equal(licence.severity,"critical");assert.match(licence.correction,/authority/i)});
test("structured drafts are scored as rendered CV text rather than JSON",()=>{const text=cvDraftToScoringText({personalDetails:{email:"nurse@example.com",phone:"+971 501234567"},summary:"Registered nurse",experiences:[{position:"Staff Nurse",achievements:[{value:"Delivered care to 20 patients per shift"}]}],educations:[{degree:"BSc Nursing"}],skills:[{field:"Clinical competencies",items:[{value:"Patient assessment"}]}],certificates:[{certificate:"DHA eligibility"}]});assert.match(text,/PROFESSIONAL EXPERIENCE/);assert.match(text,/LICENCES AND CERTIFICATIONS/);assert.doesNotMatch(text,/\{"personalDetails"/)});
test("score comparisons never conceal a regression as zero lift",()=>{assert.deepEqual(compareAtsScores(68,59),{delta:-9,direction:"regressed"});assert.deepEqual(compareAtsScores(68,74),{delta:6,direction:"improved"})});
