import { useState } from "react";
import { FiAlertCircle, FiCheckCircle, FiCopy, FiEdit3, FiZap } from "react-icons/fi";
import { requestAIDraft } from "../services/ai";
import "../css/healthcare-tools.css";
import "../css/ai-assistant.css";

const tasks={summary:"Professional summary",experience_bullets:"Employment bullets",cover_letter:"Cover letter",application_email:"Application email",linkedin_about:"LinkedIn About",recruiter_intro:"Recruiter introduction",interview_questions:"Interview questions",career_gap:"Career-gap explanation"};
const getProfile=()=>{try{return JSON.parse(sessionStorage.getItem("healthcare_profile_draft"))||{}}catch{return {}}};
export default function AIAssistant(){const [task,setTask]=useState("summary"),[facts,setFacts]=useState(""),[jobDescription,setJobDescription]=useState(""),[draft,setDraft]=useState(""),[state,setState]=useState({loading:false,error:""});const profile=getProfile();const generate=async()=>{setState({loading:true,error:""});try{const result=await requestAIDraft({task,profile:{...profile,licenceStatus:profile.licence?.status},facts,jobDescription});setDraft(result.content);setState({loading:false,error:""})}catch(error){setState({loading:false,error:error.message})}};return <main className="tool-page"><section className="tool-hero"><span>SAFE HEALTHCARE AI ASSISTANCE</span><h1>Turn verified facts into a stronger application draft.</h1><p>The assistant is instructed not to invent clinical experience, licences or metrics. Every output remains an editable draft requiring your approval.</p></section><section className="builder-grid"><div className="builder-form ai-form"><h2><FiZap/> Draft settings</h2><label>What do you want to create?<select value={task} onChange={e=>setTask(e.target.value)}>{Object.entries(tasks).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label className="full-field">Your verified facts<textarea value={facts} onChange={e=>setFacts(e.target.value)} placeholder="Add only true duties, skills, licences, achievements and measurable details. If you do not know a number, leave it out."/></label><label className="full-field">Target job description (optional)<textarea value={jobDescription} onChange={e=>setJobDescription(e.target.value)} placeholder="Paste the vacancy for country- and role-aware tailoring."/></label><button type="button" className="continue-button" disabled={state.loading} onClick={generate}><FiZap/>{state.loading?"Creating draft...":"Create verified-facts draft"}</button>{state.error&&<p className="form-error"><FiAlertCircle/>{state.error}</p>}</div><article className="letter-preview"><div className="preview-toolbar"><span>EDITABLE DRAFT</span>{draft&&<button onClick={()=>navigator.clipboard.writeText(draft)}><FiCopy/>Copy</button>}</div>{draft?<textarea className="ai-output" value={draft} onChange={e=>setDraft(e.target.value)}/>:<div className="empty-draft"><FiEdit3/><h2>Your draft will appear here</h2><p>Add your verified facts and choose the required document.</p></div>}<p className="quality-note"><FiCheckCircle/>Verify every clinical, licensing and achievement statement before use. Never include patient-identifying information.</p></article></section></main>}
