import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { FiAlertCircle, FiArrowRight, FiCheckCircle, FiInfo, FiSearch } from "react-icons/fi";
import { countryGuidance, healthcareRoles } from "../data/healthcareContent";
import { scoreHealthcareCV } from "../utils/atsScoring";
import "../css/healthcare-tools.css";
import "../css/ats-report.css";

const scoreLabels={atsReadability:"ATS readability",jobMatch:"JD match",clinicalRelevance:"Clinical relevance",credentialMatch:"Licence match",achievementStrength:"Achievement strength",profileCompleteness:"Completeness"};
export default function ATSChecker(){
 const [role,setRole]=useState(Object.keys(healthcareRoles)[0]);const [country,setCountry]=useState("UAE");const [cvText,setCvText]=useState("");const [jobDescription,setJobDescription]=useState("");
 const authority=countryGuidance[country]?.authorities?.[0]||"";
 const report=useMemo(()=>scoreHealthcareCV({cvText,jobDescription,roleConfig:healthcareRoles[role],licenceAuthority:authority}),[cvText,jobDescription,role,authority]);
 return <main className="tool-page"><section className="tool-hero"><span>TRANSPARENT HEALTHCARE ATS CHECK</span><h1>See what was found, what is missing and why.</h1><p>Every score comes from visible checks—not a random number. Paste plain CV text and optionally the target vacancy.</p></section><section className="ats-grid"><div className="ats-input"><label>Target profession<select value={role} onChange={e=>setRole(e.target.value)}>{Object.keys(healthcareRoles).map(x=><option key={x}>{x}</option>)}</select></label><label>Target country<select value={country} onChange={e=>setCountry(e.target.value)}>{Object.keys(countryGuidance).map(x=><option key={x}>{x}</option>)}</select></label><label>CV text<textarea value={cvText} onChange={e=>setCvText(e.target.value)} placeholder="Paste the text from your CV here..."/></label><label>Job description (recommended)<textarea className="jd-text" value={jobDescription} onChange={e=>setJobDescription(e.target.value)} placeholder="Paste the target vacancy for explainable keyword matching..."/></label><p className="privacy-inline"><FiInfo/>Analysis runs in your browser. Remove patient-identifying and private document information.</p></div><article className="ats-report"><div className={`ats-score ${report.score>=70?"good":""}`}><strong>{cvText?report.score:0}</strong><span>/100<br/>readiness</span></div><div className="score-breakdown">{Object.entries(report.scores).map(([key,value])=><div key={key}><span>{scoreLabels[key]}</span><strong>{value===null?"Add JD":`${cvText?value:0}%`}</strong><i><b style={{width:`${cvText&&value!==null?value:0}%`}}/></i></div>)}</div><h2><FiSearch/> Explainable findings</h2>{!cvText?<p>Paste your CV to generate the report.</p>:<div className="check-results">{report.checks.map(check=><details key={check.id} open={check.severity==="critical"&&check.points<check.max}><summary>{check.points===check.max?<FiCheckCircle/>:<FiAlertCircle/>}<span><strong>{check.label}</strong><small>{check.severity} · {check.points}/{check.max} points</small></span></summary><div><p><b>Found:</b> {Array.isArray(check.found)?check.found.join(", ")||"None":check.found}</p><p><b>Missing:</b> {Array.isArray(check.missing)?check.missing.join(", ")||"None":check.missing}</p><p><b>Why it matters:</b> {check.why}</p><p><b>Recommended correction:</b> {check.correction}</p></div></details>)}</div>}<p className="disclaimer">Guidance only—not a guarantee of ATS selection or employment. Add only verified skills, licences and achievements.</p><Link className="report-action" to="/get-started">Improve in CV Builder <FiArrowRight/></Link></article></section></main>
}
