import { useMemo, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { FiArrowRight, FiBriefcase, FiCheckCircle, FiClipboard, FiCopy, FiDollarSign, FiGlobe, FiSearch, FiShare2, FiTarget, FiTrash2 } from "react-icons/fi";
import { cvExamples, gccAuthorities, interviewQuestions, salaryData } from "../data/careerResourceData";
import "../css/career-resources.css";

const routes={
  "/healthcare-cv-examples":"examples","/gcc-eligibility-checker":"gcc","/healthcare-interview-questions":"questions","/healthcare-salary-explorer":"salary","/application-tracker":"tracker","/career-readiness-score":"score"
};
const resources=[
  ["examples","CV Examples",<FiClipboard/>,"20 role and country-specific structures"],["matcher","AI Job Matcher",<FiSearch/>,"Compare your CV with a vacancy"],["gcc","GCC Checklist",<FiGlobe/>,"Prepare your licensing documents"],["questions","Interview Questions",<FiBriefcase/>,"Role-specific questions and frameworks"],["salary","Salary Explorer",<FiDollarSign/>,"Indicative role and country ranges"],["tracker","Application Tracker",<FiTarget/>,"Keep every application organised"],["score","Readiness Score",<FiShare2/>,"Get and share a privacy-safe score"]
];
const pathFor=id=>id==="matcher"?"/career-copilot":Object.keys(routes).find(path=>routes[path]===id);

export default function CareerResources(){
 const section=routes[useLocation().pathname]||"examples";
 return <main className="resource-page"><section className="resource-hero"><span>FREE HEALTHCARE CAREER RESOURCES</span><h1>Practical tools for your next healthcare application.</h1><p>Explore credible examples, prepare your documents, practise questions and organise your job search—then use AI when you need personalised help.</p></section><nav className="resource-nav" aria-label="Career resources">{resources.map(([id,label,icon,note])=><Link className={section===id?"active":""} to={pathFor(id)} key={id}>{icon}<span><strong>{label}</strong><small>{note}</small></span></Link>)}</nav>{section==="examples"?<Examples/>:section==="gcc"?<Gcc/>:section==="questions"?<Questions/>:section==="salary"?<Salary/>:section==="tracker"?<Tracker/>:<Score/>}</main>
}

function Examples(){const [q,setQ]=useState("");const list=useMemo(()=>cvExamples.filter(x=>`${x.title} ${x.country} ${x.profession}`.toLowerCase().includes(q.toLowerCase())),[q]);return <section className="resource-panel"><header><div><span>20 COMPLETE STARTING POINTS</span><h2>Healthcare CV example library</h2><p>Every example explains the evidence recruiters expect. Never copy claims that are not true for you.</p></div><label className="resource-search"><FiSearch/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search nurse, doctor, UAE…"/></label></header><div className="example-grid">{list.map(x=><article key={x.id}><div><span>{x.profession}</span><em>{x.country}</em></div><h3>{x.title} CV</h3><p>{x.focus}</p><h4>Recommended structure</h4><ol><li>Professional profile</li><li>Registration and credentials</li><li>Core role competencies</li><li>Evidence-led experience</li><li>Education and development</li></ol><Link to="/ats-checker">Improve my CV <FiArrowRight/></Link></article>)}</div></section>}

function Gcc(){const [country,setCountry]=useState("UAE");const [profession,setProfession]=useState("Registered Nurse");const [checked,setChecked]=useState([]);const data=gccAuthorities[country];const toggle=i=>setChecked(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i]);return <section className="resource-panel narrow"><header><div><span>INFORMATIONAL PREPARATION TOOL</span><h2>GCC eligibility and document checklist</h2><p>This checklist supports preparation; only the regulator can confirm eligibility.</p></div></header><div className="selector-row"><label>Target country<select value={country} onChange={e=>{setCountry(e.target.value);setChecked([])}}>{Object.keys(gccAuthorities).map(x=><option key={x}>{x}</option>)}</select></label><label>Profession<select value={profession} onChange={e=>setProfession(e.target.value)}><option>Registered Nurse</option><option>Doctor / Physician</option><option>Pharmacist</option><option>Allied Health Professional</option><option>Medical Laboratory Professional</option></select></label></div><div className="checklist-card"><span>LIKELY AUTHORITY</span><h3>{data.authority}</h3><p>{profession} · {country}</p>{data.steps.map((step,i)=><label className="check-row" key={step}><input type="checkbox" checked={checked.includes(i)} onChange={()=>toggle(i)}/><i><FiCheckCircle/></i><span>{step}</span></label>)}<div className="progress-line"><i style={{width:`${checked.length/data.steps.length*100}%`}}/></div><strong>{checked.length} of {data.steps.length} preparation steps reviewed</strong></div><Link className="resource-cta" to="/gulf-healthcare-cv">Build my GCC-ready CV <FiArrowRight/></Link><p className="resource-disclaimer">Requirements change. Verify all information with the relevant official authority before paying fees or submitting documents.</p></section>}

function Questions(){const [category,setCategory]=useState("All");const cats=["All",...new Set(interviewQuestions.map(x=>x[0]))];const list=category==="All"?interviewQuestions:interviewQuestions.filter(x=>x[0]===category);return <section className="resource-panel"><header><div><span>FREE PRACTICE LIBRARY</span><h2>Healthcare interview questions</h2><p>Use the framework to structure your own true example, then practise it with the AI coach.</p></div><select value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(x=><option key={x}>{x}</option>)}</select></header><div className="question-list">{list.map(([cat,q,tip],i)=><article key={`${cat}-${i}`}><span>{cat}</span><h3>{q}</h3><p><strong>Answer framework:</strong> {tip}</p><Link to="/interview-coach">Practise with AI <FiArrowRight/></Link></article>)}</div></section>}

function Salary(){const [role,setRole]=useState("All");const roles=["All",...new Set(salaryData.map(x=>x.role))];const list=role==="All"?salaryData:salaryData.filter(x=>x.role===role);return <section className="resource-panel"><header><div><span>INDICATIVE MARKET RANGES</span><h2>Healthcare salary explorer</h2><p>Use these broad ranges for orientation—not as an offer prediction.</p></div><select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(x=><option key={x}>{x}</option>)}</select></header><div className="salary-grid">{list.map((x,i)=><article key={`${x.role}-${x.country}-${i}`}><span>{x.country}</span><h3>{x.role}</h3><strong>{x.range}</strong><p>Indicative gross range; specialty, licence, facility, benefits and experience can materially change pay.</p></article>)}</div><p className="resource-disclaimer">Ranges are editorial estimates for planning and may become outdated. Confirm current compensation using employers, recruiters and official labour-market sources.</p></section>}

function Tracker(){const load=()=>{try{return JSON.parse(localStorage.getItem("resuai_applications"))||[]}catch{return[]}};const [items,setItems]=useState(load);const [form,setForm]=useState({employer:"",role:"",country:"UAE",status:"Planned"});const save=next=>{setItems(next);localStorage.setItem("resuai_applications",JSON.stringify(next))};const add=e=>{e.preventDefault();if(!form.employer.trim()||!form.role.trim())return;save([{...form,id:Date.now(),date:new Date().toISOString().slice(0,10)},...items]);setForm({...form,employer:"",role:""})};return <section className="resource-panel narrow"><header><div><span>PRIVATE ON THIS DEVICE</span><h2>Healthcare application tracker</h2><p>Track roles, countries and progress. Entries remain in this browser.</p></div></header><form className="tracker-form" onSubmit={add}><input aria-label="Employer" placeholder="Hospital or employer" value={form.employer} onChange={e=>setForm({...form,employer:e.target.value})}/><input aria-label="Role" placeholder="Target role" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/><select value={form.country} onChange={e=>setForm({...form,country:e.target.value})}><option>UAE</option><option>Saudi Arabia</option><option>Qatar</option><option>Oman</option><option>India</option><option>United Kingdom</option><option>Other</option></select><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Planned</option><option>Applied</option><option>Interview</option><option>Offer</option><option>Closed</option></select><button>Add application</button></form><div className="tracker-list">{items.length?items.map(x=><article key={x.id}><div><span>{x.status}</span><h3>{x.role}</h3><p>{x.employer} · {x.country} · {x.date}</p></div><button aria-label={`Remove ${x.role}`} onClick={()=>save(items.filter(y=>y.id!==x.id))}><FiTrash2/></button></article>):<div className="empty-resource"><FiBriefcase/><h3>No applications added yet</h3><p>Add your first target role above.</p></div>}</div></section>}

function Score(){const [checks,setChecks]=useState({cv:false,licence:false,jd:false,cover:false,interview:false,tracker:false});const total=Object.values(checks).filter(Boolean).length;const score=Math.round(total/6*100);const text=`My healthcare career readiness score is ${score}/100 on ResuAIBuilder.`;const share=async()=>{if(navigator.share)await navigator.share({title:"Healthcare Career Readiness",text,url:location.origin+"/career-readiness-score"});else await navigator.clipboard.writeText(`${text} ${location.origin}/career-readiness-score`)};return <section className="resource-panel narrow"><header><div><span>PRIVACY-SAFE SELF-ASSESSMENT</span><h2>Healthcare career readiness score</h2><p>No CV details are included in the score or shared message.</p></div></header><div className="score-card"><div className="score-ring" style={{"--score":`${score*3.6}deg`}}><strong>{score}</strong><small>/100</small></div><div>{Object.entries({cv:"My CV is current and ATS-readable",licence:"My licence status is stated accurately",jd:"I have matched my CV to the vacancy",cover:"My cover letter is role-specific",interview:"I have practised interview answers",tracker:"I am tracking applications and follow-ups"}).map(([key,label])=><label className="score-check" key={key}><input type="checkbox" checked={checks[key]} onChange={e=>setChecks({...checks,[key]:e.target.checked})}/><span>{label}</span></label>)}</div></div><div className="score-actions"><button onClick={share}><FiShare2/> Share my score</button><button onClick={()=>navigator.clipboard.writeText(text)}><FiCopy/> Copy result</button><Link to="/ats-checker">Improve my readiness <FiArrowRight/></Link></div></section>}
