import { useMemo, useState } from "react";
import { FiCheckCircle, FiCopy, FiDownload, FiFileText } from "react-icons/fi";
import { healthcareRoles } from "../data/healthcareContent";
import "../css/healthcare-tools.css";

const empty={name:"",role:"Registered Nurse",targetRole:"",employer:"",experience:"",strengths:"",achievement:"",jobKeywords:""};
const buildLetter=f=>`Dear Hiring Manager,\n\nI am writing to apply for the ${f.targetRole||f.role} position at ${f.employer||"your organisation"}. As a ${f.role.toLowerCase()}${f.experience?` with ${f.experience} of experience`:""}, I offer ${f.strengths||"a strong commitment to safe, compassionate and evidence-based care"}.\n\nIn my recent work, ${f.achievement||"I have collaborated with multidisciplinary teams to deliver reliable care while maintaining accurate documentation and professional standards"}. This experience has strengthened my ability to contribute effectively in demanding healthcare environments.${f.jobKeywords?` My background also aligns with your requirements for ${f.jobKeywords}.`:""}\n\nI am particularly interested in ${f.employer||"your organisation"} because of the opportunity to contribute to high-quality patient care and continuous improvement. I would welcome the chance to discuss how my clinical experience, professional values and commitment to patient safety can support your team.\n\nThank you for considering my application.\n\nSincerely,\n${f.name||"Your Name"}`;

export default function CoverLetter(){const [form,setForm]=useState(empty);const [copied,setCopied]=useState(false);const letter=useMemo(()=>buildLetter(form),[form]);const set=(k,v)=>setForm(p=>({...p,[k]:v}));const copy=async()=>{await navigator.clipboard.writeText(letter);setCopied(true);setTimeout(()=>setCopied(false),1500)};const download=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([letter],{type:"text/plain"}));a.download=`${form.name||"healthcare"}-cover-letter.txt`;a.click();URL.revokeObjectURL(a.href)};return <main className="tool-page"><section className="tool-hero"><span>HEALTHCARE COVER LETTER BUILDER</span><h1>Create a focused letter for every vacancy.</h1><p>Connect your clinical experience, strongest evidence and the employer’s priorities in a clear professional letter.</p></section><section className="builder-grid"><form className="builder-form"><h2><FiFileText/> Application details</h2><label>Your name<input value={form.name} onChange={e=>set("name",e.target.value)} placeholder="e.g. Aisha Khan"/></label><label>Your profession<select value={form.role} onChange={e=>set("role",e.target.value)}>{Object.keys(healthcareRoles).map(x=><option key={x}>{x}</option>)}</select></label><label>Position you are applying for<input value={form.targetRole} onChange={e=>set("targetRole",e.target.value)} placeholder="e.g. ICU Staff Nurse"/></label><label>Employer / hospital<input value={form.employer} onChange={e=>set("employer",e.target.value)} placeholder="e.g. City Medical Centre"/></label><label>Years of experience<input value={form.experience} onChange={e=>set("experience",e.target.value)} placeholder="e.g. 5 years"/></label><label>Top strengths<textarea value={form.strengths} onChange={e=>set("strengths",e.target.value)} placeholder="Critical care, patient education and clinical documentation"/></label><label>One measurable achievement<textarea value={form.achievement} onChange={e=>set("achievement",e.target.value)} placeholder="Reduced medication delays by 20% through..."/></label><label>Keywords from the vacancy<textarea value={form.jobKeywords} onChange={e=>set("jobKeywords",e.target.value)} placeholder="Patient assessment, EMR, infection control"/></label></form><article className="letter-preview"><div className="preview-toolbar"><span>LIVE LETTER PREVIEW</span><div><button onClick={copy}><FiCopy/>{copied?"Copied":"Copy"}</button><button onClick={download}><FiDownload/>Download</button></div></div><pre>{letter}</pre><p className="quality-note"><FiCheckCircle/>Tip: replace general statements with one verified clinical or operational achievement.</p></article></section></main>}
