const q=(question,options,answer,explanation)=>({question,options,answer,explanation});
const common=[
q("A competent patient withdraws consent immediately before a procedure. What should the team do first?",["Proceed because consent was signed","Pause and inform the responsible clinician","Ask a relative to consent","Complete the procedure then document"],1,"Consent is ongoing and may be withdrawn. Pause and escalate appropriately."),
q("A medicine was administered to the wrong patient. What is the immediate priority?",["Alter the record","Assess the patient and escalate","Wait for symptoms","Tell only the next shift"],1,"Immediate assessment and escalation protect the patient before reporting and documentation."),
q("Which measure most directly reduces healthcare-associated infection transmission?",["Routine antibiotics","Hand hygiene at indicated moments","Double gloves for every task","Universal isolation"],1,"Correct hand hygiene is a core infection-prevention control."),
q("A colleague requests patient results through a personal messaging account. What is safest?",["Send abnormal values only","Use an approved secure clinical channel","Send then delete","Ask the patient to forward it"],1,"Confidential data belongs only in authorised secure systems."),
q("A patient becomes suddenly unresponsive. What is the best initial approach?",["Finish documentation","Assess responsiveness and activate emergency support","Call the family","Wait for the senior round"],1,"Recognise the emergency, begin immediate assessment and summon appropriate help."),
q("What is the best response to a near miss that caused no patient harm?",["Ignore it","Report it through the approved safety system","Delete related records","Discuss it only socially"],1,"Near-miss reporting supports learning and prevention."),
q("Which documentation entry is most appropriate?",["A factual, timed record of assessment and action","An entry written by a colleague","An altered retrospective note without explanation","A personal opinion about the patient"],0,"Clinical records should be timely, factual, attributable and compliant with policy."),
q("A language barrier affects consent. What should be arranged?",["A child relative","An approved interpreter","A guess based on gestures","Consent without discussion"],1,"An approved interpreter supports accurate communication and valid consent.")
];
export const banks={
Nurse:[
q("Which finding needs the most urgent nursing escalation?",["Pain improves from 6 to 3","New stridor with increased work of breathing","A request for a blanket","Routine medicine due soon"],1,"New airway compromise is an immediate priority."),
q("A patient has falling blood pressure and altered mental status. What is safest?",["Complete routine paperwork","Use ABCDE and escalate","Offer oral fluids automatically","Recheck after the shift"],1,"ABCDE identifies immediate threats while help is summoned."),
q("Before administering insulin, the nurse should prioritise:",["Room number only","Patient identity, prescription, glucose and meal timing","The previous shift's memory","Family preference"],1,"Insulin requires identity, prescription and clinical-context checks."),
q("A pressure injury risk assessment is high. What is the best plan?",["Wait for skin breakdown","Implement an individual prevention plan and reassess","Massage red skin","Use one intervention only"],1,"Prevention combines risk-based repositioning, skin care, support surfaces and reassessment."),
q("A post-operative patient develops sudden dyspnoea and tachycardia. What should the nurse do?",["Encourage walking alone","Stop, assess and escalate urgently","Offer food","Document for tomorrow"],1,"Sudden respiratory deterioration needs immediate assessment and escalation."),
q("During handover, which information is most important?",["Only the diagnosis","Current risks, changes, pending actions and escalation plan","Personal opinions","Unrelated ward news"],1,"Safe handover communicates current clinical risk and required action."),
q("A conscious patient has signs of hypoglycaemia. What is appropriate first?",["Ignore until the next round","Follow the approved hypoglycaemia protocol and recheck","Give long-acting insulin","Restrict all carbohydrate"],1,"Prompt protocol-based treatment and reassessment reduce harm."),
q("A patient at high falls risk wants to mobilise. What is best?",["Restrain the patient","Assess, explain risk and provide appropriate assistance","Refuse all mobility","Allow unassisted walking"],1,"Use proportionate, person-centred risk controls rather than unnecessary restriction.")
],
Doctor:[
q("Sudden chest pain, hypotension and hypoxia require:",["Routine follow-up","ABCDE stabilisation with parallel urgent investigation","Discharge advice","History only before any action"],1,"Stabilisation and evaluation of life-threatening causes happen in parallel."),
q("Before prescribing in renal impairment, review:",["Only age","Renal function, indication and trusted dose guidance","Patient preference alone","The standard dose automatically"],1,"Renal clearance affects safe medicine selection and dosing."),
q("A patient lacks decision-making capacity for an urgent intervention. What is best?",["Do nothing","Follow applicable capacity, best-interest and emergency policy","Ask any visitor","Sign for the patient"],1,"Use the legal and organisational framework while addressing urgent risk."),
q("An antibiotic is requested without evidence of bacterial infection. What is best?",["Prescribe automatically","Assess indication and follow stewardship guidance","Use the broadest drug","Skip allergy review"],1,"Antimicrobial stewardship requires a justified indication and appropriate selection."),
q("A critical diagnostic result conflicts with the clinical picture. What should happen?",["Ignore it","Reassess the patient and verify/escalate the result","Delete the result","Wait for discharge"],1,"Unexpected critical data requires clinical reassessment and verification."),
q("A colleague asks you to backdate a note. What is appropriate?",["Backdate it","Make a clearly identified current late entry per policy","Use another person's login","Avoid documenting"],1,"Late documentation must remain transparent and attributable."),
q("Which discharge action best supports safety?",["No written plan","Medication reconciliation, red flags and follow-up communication","Stop all medicines","Use unexplained abbreviations"],1,"Safe discharge includes reconciled treatment and clear follow-up."),
q("A diagnostic error is suspected after treatment begins. What is best?",["Conceal it","Reassess, mitigate harm and escalate transparently","Continue unchanged","Delete earlier notes"],1,"Patient safety requires prompt reassessment, mitigation and honest escalation.")
],
Pharmacist:[
q("A prescription dose appears ten times higher than usual. What should happen?",["Dispense because it is signed","Hold and clarify with the prescriber","Reduce it secretly","Ask the patient to test it"],1,"A potentially unsafe dose must be clarified before supply."),
q("Which practice supports high-alert medication safety?",["Memory alone","Required independent checks and clear labelling","Store look-alikes together","Bypass alerts"],1,"Independent checks and clear identification reduce preventable harm."),
q("A patient reports a serious penicillin allergy and receives an amoxicillin prescription. What is best?",["Dispense immediately","Hold and clarify the allergy and prescription","Remove the allergy record","Tell the patient to try one dose"],1,"A possible serious allergy conflict requires clarification before supply."),
q("Which counselling point is essential for a new anticoagulant?",["No monitoring or precautions matter","Explain dosing, missed doses, bleeding signs and interactions","Double every missed dose","Stop without advice"],1,"Safe anticoagulant use depends on adherence and recognition of bleeding risk."),
q("A refrigerator medicine was outside range for an unknown period. What should happen?",["Dispense it","Quarantine and assess using approved stability guidance","Freeze it","Change the temperature log"],1,"Potential cold-chain breaches require quarantine and documented assessment."),
q("Two products have similar names and packaging. The best control is:",["Store them together","Use segregation, alerts and careful selection checks","Remove labels","Rely on colour"],1,"Layered controls reduce look-alike/sound-alike errors."),
q("A patient requests an early controlled-medicine refill. What is best?",["Supply without review","Check legal, clinical and organisational requirements and refer concerns","Alter the date","Use another patient's supply"],1,"Controlled medicines require compliant review and documentation."),
q("A clinically significant interaction appears during dispensing. What should the pharmacist do?",["Override automatically","Assess relevance and clarify or counsel as appropriate","Delete the alert","Tell the patient nothing"],1,"Interaction alerts require professional assessment and appropriate action.")
],
"Pharmacy Technician":[
q("Product strength differs from the prescription. What should the technician do?",["Change the prescription","Stop and refer to the pharmacist","Supply the nearest strength","Ask the patient to calculate"],1,"Discrepancies must be referred through the pharmacist-led checking process."),
q("Which stock method reduces expiry risk?",["Newest first","First-expiry, first-out with routine checks","Mix returns with stock","Remove batch data"],1,"FEFO and date checks support safe inventory control."),
q("A dispensed label has the wrong patient name. What is best?",["Cover it with another label","Stop the process and refer for correction and checking","Give verbal advice only","Supply it anyway"],1,"Identification errors require correction and a complete recheck."),
q("A returned medicine is sealed and looks unused. What should happen?",["Return it to saleable stock automatically","Follow the approved returns and disposal policy","Give it to another patient","Remove its batch number"],1,"Storage conditions cannot usually be assured after supply."),
q("A controlled-drug balance does not reconcile. What is best?",["Adjust it silently","Stop and report through the approved discrepancy process","Wait one month","Delete the entry"],1,"Controlled-drug discrepancies require immediate, documented escalation."),
q("During final collection, two patients share a surname. What is safest?",["Use surname only","Verify approved identifiers before handover","Ask who arrived first","Show both prescriptions"],1,"Use sufficient identifiers to prevent wrong-patient supply."),
q("A medicine recall notice arrives. The first action is to:",["Ignore it","Identify and quarantine affected stock per procedure","Relabel stock","Sell it quickly"],1,"Recall procedures protect patients by controlling affected stock."),
q("A technician is asked for a clinical recommendation beyond their role. What is best?",["Guess","Refer to the pharmacist","Search social media","Avoid helping"],1,"Work within scope and refer clinical decisions appropriately.")
],
Physiotherapist:[
q("Sudden calf swelling with shortness of breath during rehabilitation requires:",["Continue exercise","Stop and seek urgent medical assessment","Massage the calf","Review next week"],1,"These red flags may indicate thromboembolism."),
q("Best evidence of rehabilitation progress is:",["General impression only","Baseline and repeat appropriate outcome measures","Changing goals each visit","No functional record"],1,"Consistent outcome measures support safe clinical decisions."),
q("New saddle numbness and bladder dysfunction suggest:",["Routine muscle soreness","Urgent spinal red-flag escalation","Normal recovery","A need for massage"],1,"These symptoms can indicate cauda equina syndrome."),
q("A patient becomes dizzy on standing. What should happen?",["Continue walking","Support safety, reassess observations and escalate as needed","Leave them alone","Increase exercise intensity"],1,"Prevent a fall and assess possible orthostatic or clinical deterioration."),
q("Before using an unfamiliar modality, the therapist should:",["Try it immediately","Confirm competence, indication, contraindications and consent","Copy a colleague","Skip documentation"],1,"Safe care requires competence and patient-specific risk assessment."),
q("A rehabilitation goal should be:",["Vague and fixed forever","Meaningful, measurable and reviewed with the patient","Chosen without the patient","Based only on equipment"],1,"Collaborative measurable goals guide person-centred care."),
q("Pain rapidly worsens with new neurological weakness. What is best?",["Push through","Stop and arrange urgent assessment","Apply heat only","Book routine review"],1,"Progressive neurological deficit is a red flag."),
q("Which transfer approach is safest?",["Manual lift regardless of risk","Use assessed technique and equipment with adequate assistance","Ask family to improvise","Move quickly without explanation"],1,"Risk assessment and appropriate equipment protect patient and staff.")
],
"Medical Laboratory Professional":[
q("Specimen label and request details do not match. What is safest?",["Relabel from memory","Follow discrepancy or rejection procedure","Run it then correct","Remove identifiers"],1,"Identification errors require the approved process."),
q("A critical result is obtained. What should happen?",["Routine reporting later","Verify as required and communicate under critical-result policy","Post in a group chat","Delete it"],1,"Critical results need timely verified communication and documentation."),
q("Quality-control results are outside acceptable limits. What is best?",["Release patient results","Stop, investigate and resolve before release","Change the limits","Ignore one failure"],1,"Failed QC can invalidate patient results."),
q("A haemolysed sample may affect the requested analyte. What should happen?",["Report without comment","Assess against laboratory policy and request recollection if required","Dilute automatically","Hide the haemolysis"],1,"Pre-analytical interference must be managed under validated policy."),
q("A reagent lot changes. Safe practice includes:",["Immediate unverified use","Required lot verification before routine reporting","Removing controls","Using expired calibrators"],1,"Lot verification confirms acceptable performance."),
q("Patient data is visible on an unattended screen. What is best?",["Leave it open","Secure the workstation immediately","Photograph it","Share the login"],1,"Access controls protect confidential laboratory information."),
q("A result is amended after release. What is required?",["Silent replacement","Traceable correction and prompt communication when clinically important","Delete audit history","Use another user's account"],1,"Amended reports must be transparent and communicated appropriately."),
q("Which action supports specimen traceability?",["Removing timestamps","Documented identifiers, receipt, processing and storage chain","Shared unlabeled containers","Memory alone"],1,"End-to-end traceability supports accurate results and investigation.")
],
Radiographer:[
q("Before ionising-radiation imaging, which check is fundamental?",["Room number","Correct patient, examination, justification and safety status","Ability to pay","Referrer seniority"],1,"Identification, justification and safety screening precede exposure."),
q("ALARA means exposure should be:",["As long as resources allow","As low as reasonably achievable","The same for everyone","Avoided only in children"],1,"Optimisation minimises exposure while achieving the clinical purpose."),
q("Pregnancy status is uncertain before a relevant exposure. What is best?",["Proceed without discussion","Follow the approved pregnancy-screening procedure","Ask another patient","Cancel every examination"],1,"Use the formal risk and justification pathway."),
q("Contrast extravasation is suspected. What should happen?",["Ignore it","Stop injection, assess and follow escalation protocol","Increase flow","Send the patient home immediately"],1,"Prompt assessment and protocol-based management reduce harm."),
q("A patient identity check fails. What is best?",["Use room number","Do not expose until identity is resolved","Ask a visitor only","Guess from the image request"],1,"Positive identification is mandatory before imaging."),
q("A portable examination is requested in a crowded bay. What is safest?",["Expose immediately","Control the area and apply radiation-protection measures","Remove shielding rules","Ask everyone to stay close"],1,"Time, distance and shielding protect others."),
q("An image is technically inadequate. The repeat decision should be based on:",["Routine repetition","Clinical need, optimisation and local repeat policy","Patient age only","Convenience"],1,"Avoid unnecessary repeat exposure while ensuring diagnostic adequacy."),
q("After contrast, a patient develops breathing difficulty. What is best?",["Offer water only","Activate the emergency response and assess immediately","Continue scanning","Ask them to wait outside"],1,"Possible severe contrast reaction needs immediate emergency management.")
]};
export const professions=Object.keys(banks);
export const fullBank=profession=>[...(banks[profession]||banks.Nurse),...common];
