/* global process */
const roles={all:"healthcare",nurse:"registered nurse",doctor:"doctor physician",pharmacist:"pharmacist",dentist:"dentist",physiotherapist:"physiotherapist",laboratory:"medical laboratory technician",radiographer:"radiographer",coder:"medical coder",assistant:"healthcare assistant"};
const locations={uae:"United Arab Emirates",dubai:"Dubai","abu-dhabi":"Abu Dhabi",sharjah:"Sharjah",ajman:"Ajman","al-ain":"Al Ain","ras-al-khaimah":"Ras Al Khaimah",fujairah:"Fujairah"};
const roleTitleTerms={nurse:/\b(nurs|midwi|clinical facilitator)\w*/i,doctor:/\b(doctor|physician|consultant|specialist|medical officer|surgeon|paediatric|pediatric)\w*/i,pharmacist:/\b(pharmac|pharmacy)\w*/i,dentist:/\b(dent|orthodont|prosthodont|periodont)\w*/i,physiotherapist:/\b(physiotherap|physical therap)\w*/i,laboratory:/\b(laborator|lab techn|patholog|phlebotom)\w*/i,radiographer:/\b(radiograph|radiolog|imaging|sonograph)\w*/i,coder:/\b(medical cod|clinical cod|medical bill)\w*/i,assistant:/\b(healthcare assistant|health care assistant|nursing assistant|caregiver|patient care assistant)\w*/i};
const healthcareTitleTerms=/\b(nurs\w*|midwi\w*|doctor\w*|physician\w*|medical officer\w*|surgeon\w*|consultant\w*|specialist\w*|paediatric\w*|pediatric\w*|pharmac\w*|pharmacy\w*|dent\w*|orthodont\w*|physiotherap\w*|physical therap\w*|occupational therap\w*|speech therap\w*|radiograph\w*|radiolog\w*|sonograph\w*|imaging\w*|laborator\w*|lab techn\w*|patholog\w*|phlebotom\w*|medical cod\w*|clinical cod\w*|medical bill\w*|healthcare assistant\w*|health care assistant\w*|nursing assistant\w*|caregiver\w*|patient care assistant\w*|respiratory therap\w*|dietitian\w*|nutritionist\w*|optomet\w*|audiolog\w*|paramedic\w*|emergency medical technician\w*|hospital\w*|clinic\w*|medical receptionist\w*)\b/i;
const allRoleSearchTerms=["nurse","doctor","pharmacist","medical laboratory","physiotherapist","radiographer"];
const roleSearchTerms={nurse:["registered nurse","staff nurse","nurse"],doctor:["doctor","physician","medical officer"],pharmacist:["pharmacist","pharmacy"],dentist:["dentist","dental"],physiotherapist:["physiotherapist","physical therapist"],laboratory:["medical laboratory","lab technician"],radiographer:["radiographer","radiology technician"],coder:["medical coder","medical billing"],assistant:["healthcare assistant","nursing assistant","caregiver"]};
const foreignCountry=/\b(oman|saudi arabia|qatar|bahrain|kuwait|united states|usa|united kingdom|uk|canada|australia|india|pakistan)\b/i,uaeLocation=/\b(united arab emirates|uae|dubai|abu dhabi|sharjah|ajman|al ain|ras al khaimah|fujairah|umm al quwain)\b/i;
const locationTerms={dubai:/\bdubai\b/i,"abu-dhabi":/\babu dhabi\b/i,sharjah:/\bsharjah\b/i,ajman:/\bajman\b/i,"al-ain":/\bal ain\b/i,"ras-al-khaimah":/\bras al khaimah\b/i,fujairah:/\bfujairah\b/i};
const memoryCache=new Map(),CACHE_MS=30*60*1000,CACHE_VERSION="v13-multi-provider-feed",MAX_JOB_AGE_DAYS=7,FUTURE_TOLERANCE_MS=6*60*60*1000,JSEARCH_MAX_TERMS=1,JOOBLE_MAX_TERMS=2,ADZUNA_MAX_TERMS=2;
const safeText=(v,m=5000)=>typeof v==="string"?v.trim().slice(0,m):"";
const safeUrl=v=>{try{const p=new URL(v);return p.protocol==="https:"||p.protocol==="http:"?p.toString():""}catch{return""}};
const normalizeJSearchJob=j=>({id:`jsearch:${safeText(j.job_id,280)}`,provider:"JSearch",title:safeText(j.job_title,180),employer:safeText(j.employer_name,140)||"Employer not listed",employerLogo:safeUrl(j.employer_logo),city:safeText(j.job_city,80),state:safeText(j.job_state,80),country:safeText(j.job_country,80),location:safeText(j.job_location,160),employmentType:safeText(j.job_employment_type,60),description:safeText(j.job_description),applyUrl:safeUrl(j.job_apply_link||j.apply_options?.[0]?.apply_link||j.job_google_link),publisher:safeText(j.job_publisher,100),postedAt:safeText(j.job_posted_at_datetime_utc,60),minSalary:Number.isFinite(j.job_min_salary)?j.job_min_salary:null,maxSalary:Number.isFinite(j.job_max_salary)?j.job_max_salary:null,salaryPeriod:safeText(j.job_salary_period,30)});
const normalizeJoobleJob=j=>({id:`jooble:${safeText(String(j.id||""),280)}`,provider:"Jooble",title:safeText(j.title,180),employer:safeText(j.company,140)||"Employer not listed",employerLogo:"",city:"",state:"",country:"United Arab Emirates",location:safeText(j.location,160),employmentType:safeText(j.type,60),description:safeText(j.snippet),applyUrl:safeUrl(j.link),publisher:safeText(j.source,100)||"Jooble",postedAt:safeText(j.updated,60),minSalary:null,maxSalary:null,salaryPeriod:safeText(j.salary,80)});
const normalizeAdzunaJob=j=>({id:`adzuna:${safeText(String(j.id||""),280)}`,provider:"Adzuna",title:safeText(j.title,180),employer:safeText(j.company?.display_name,140)||"Employer not listed",employerLogo:"",city:"",state:"",country:"United Arab Emirates",location:safeText(j.location?.display_name,160),employmentType:safeText(j.contract_time||j.contract_type,60),description:safeText(j.description),applyUrl:safeUrl(j.redirect_url),publisher:"Adzuna",postedAt:safeText(j.created,60),minSalary:Number.isFinite(j.salary_min)?j.salary_min:null,maxSalary:Number.isFinite(j.salary_max)?j.salary_max:null,salaryPeriod:"year"});
const dedupeKey=j=>[j.title,j.employer,j.location||j.city].map(v=>safeText(v,180).toLowerCase().replace(/[^a-z0-9]+/g," ").trim()).join(":");
const terms=r=>(r==="all"?allRoleSearchTerms:(roleSearchTerms[r]||[roles[r]]));
export const isFreshJob=(j,now=Date.now())=>{if(!j.postedAt)return false;const p=Date.parse(j.postedAt);return Number.isFinite(p)&&p<=now+FUTURE_TOLERANCE_MS&&now-p<=MAX_JOB_AGE_DAYS*86400000};
async function fetchJSearchJobs(r,l){if(!process.env.JSEARCH_API_KEY)return{provider:"JSearch",configured:false,jobs:[]};const t=terms(r).slice(0,JSEARCH_MAX_TERMS),out=[];let err;for(const q of t){try{const u=new URL("https://api.openwebninja.com/jsearch/search-v2");u.searchParams.set("query",`${q} jobs in ${locations[l]}`);u.searchParams.set("country","ae");u.searchParams.set("language","en");u.searchParams.set("num_pages","1");u.searchParams.set("date_posted","week");const a=await fetch(u,{headers:{"x-api-key":process.env.JSEARCH_API_KEY,Accept:"application/json"},signal:AbortSignal.timeout(12000)});if(!a.ok)throw new Error(`JSearch:${a.status}`);const d=await a.json();const raw=Array.isArray(d.data)?d.data:Array.isArray(d.data?.jobs)?d.data.jobs:[];out.push(...raw.map(normalizeJSearchJob))}catch(e){err=e}}if(!out.length&&err)throw err;return{provider:"JSearch",configured:true,jobs:out}}
async function fetchJoobleJobs(r,l){if(!process.env.JOOBLE_API_KEY)return{provider:"Jooble",configured:false,jobs:[]};const base=safeText(process.env.JOOBLE_API_BASE_URL,300)||"https://jooble.org/api",b=new URL(base);if(b.protocol!=="https:")throw new Error("Jooble:invalid-base-url");const endpoint=new URL(`${b.toString().replace(/\/+$/,"")}/${encodeURIComponent(process.env.JOOBLE_API_KEY)}`),out=[];let err;for(const q of terms(r).slice(0,JOOBLE_MAX_TERMS)){try{const a=await fetch(endpoint,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify({keywords:q,location:locations[l],page:"1",ResultOnPage:"25",SearchMode:"1"}),signal:AbortSignal.timeout(12000)});if(!a.ok)throw new Error(`Jooble:${a.status}`);const d=await a.json();out.push(...(Array.isArray(d.jobs)?d.jobs:[]).map(normalizeJoobleJob))}catch(e){err=e}}if(!out.length&&err)throw err;return{provider:"Jooble",configured:true,jobs:out}}
async function fetchAdzunaJobs(r,l){if(!process.env.ADZUNA_APP_ID||!process.env.ADZUNA_APP_KEY)return{provider:"Adzuna",configured:false,jobs:[]};const out=[];let err;for(const q of terms(r).slice(0,ADZUNA_MAX_TERMS)){try{const u=new URL("https://api.adzuna.com/v1/api/jobs/ae/search/1");u.searchParams.set("app_id",process.env.ADZUNA_APP_ID);u.searchParams.set("app_key",process.env.ADZUNA_APP_KEY);u.searchParams.set("results_per_page","30");u.searchParams.set("what",q);if(l!=="uae")u.searchParams.set("where",locations[l]);u.searchParams.set("max_days_old","7");u.searchParams.set("sort_by","date");u.searchParams.set("content-type","application/json");const a=await fetch(u,{headers:{Accept:"application/json"},signal:AbortSignal.timeout(12000)});if(!a.ok)throw new Error(`Adzuna:${a.status}`);const d=await a.json();out.push(...(Array.isArray(d.results)?d.results:[]).map(normalizeAdzunaJob))}catch(e){err=e}}if(!out.length&&err)throw err;return{provider:"Adzuna",configured:true,jobs:out}}
export const isRelevantUaeJob=(j,r,l)=>{const place=[j.location,j.city,j.state,j.country].filter(Boolean).join(" "),text=`${j.title} ${place} ${j.description||""}`;if(place&&foreignCountry.test(place)&&!uaeLocation.test(place))return false;if(l!=="uae"&&locationTerms[l]&&!locationTerms[l].test(place))return false;if(r==="all"&&!healthcareTitleTerms.test(j.title||""))return false;if(r!=="all"&&roleTitleTerms[r]&&!roleTitleTerms[r].test(text))return false;return true};
export async function healthcareJobsHandler(req,res){res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("Cache-Control","s-maxage=900, stale-while-revalidate=3600");if(req.method!=="GET"){res.setHeader("Allow","GET");return res.status(405).json({error:"Method not allowed"})}const r=typeof req.query.role==="string"?req.query.role:"all",l=typeof req.query.location==="string"?req.query.location:"uae";if(!roles[r]||!locations[l])return res.status(400).json({error:"Select a valid healthcare role and UAE location."});if(!process.env.JSEARCH_API_KEY&&!process.env.JOOBLE_API_KEY&&(!process.env.ADZUNA_APP_ID||!process.env.ADZUNA_APP_KEY))return res.status(503).json({jobs:[],error:"The healthcare jobs service is not configured yet."});const key=`${CACHE_VERSION}:${r}:${l}`,cached=memoryCache.get(key);if(cached&&Date.now()-cached.createdAt<CACHE_MS)return res.status(200).json({...cached.payload,cached:true});const settled=await Promise.allSettled([fetchAdzunaJobs(r,l),fetchJoobleJobs(r,l),fetchJSearchJobs(r,l)]),ok=settled.filter(x=>x.status==="fulfilled").map(x=>x.value),failed=settled.filter(x=>x.status==="rejected");failed.forEach(x=>console.error("Healthcare jobs provider failed",x.reason?.message||x.reason));const rawCounts=Object.fromEntries(ok.map(x=>[x.provider,x.jobs.length]));const usable=ok.flatMap(x=>x.jobs).filter(j=>j.title&&j.applyUrl),fresh=usable.filter(isFreshJob),relevant=fresh.filter(j=>isRelevantUaeJob(j,r,l)),seen=new Set();const jobs=relevant.filter(j=>{const k=dedupeKey(j)||j.id;if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>Date.parse(b.postedAt)-Date.parse(a.postedAt)).slice(0,100);const payload={jobs,role:r,location:l,fetchedAt:new Date().toISOString(),freshnessPolicy:{maxAgeDays:MAX_JOB_AGE_DAYS,missingDatesExcluded:true},providers:ok.filter(x=>x.configured).map(x=>x.provider),providerErrors:failed.map(x=>x.reason?.message||"provider error"),partial:failed.length>0,rawCounts,filterCounts:{usable:usable.length,fresh:fresh.length,relevant:relevant.length}};if(jobs.length)memoryCache.set(key,{createdAt:Date.now(),payload});return res.status(200).json(payload)}
