const limits=new Map(); const allowedTasks=new Set(["summary","experience_bullets","cover_letter","application_email","linkedin_about","recruiter_intro","interview_questions","career_gap"]);
const clean=value=>String(value||"").replace(/[<>]/g,"").slice(0,20000);
const rateLimited=request=>{const key=(request.headers["x-forwarded-for"]||request.socket?.remoteAddress||"unknown").split(",")[0];const now=Date.now(),entry=limits.get(key)||{start:now,count:0};if(now-entry.start>60000){entry.start=now;entry.count=0}entry.count++;limits.set(key,entry);return entry.count>10};
const system=`You write truthful healthcare career documents. Use only facts supplied by the applicant. Never invent qualifications, licences, clinical competence, patient numbers, employers or metrics. If measurable details are missing, write strong non-numeric language or mark a short [confirm detail] prompt. Never include patient-identifying or private identity information. Adapt terminology to the profession and destination. Avoid clichés and keyword stuffing. Return only the requested draft followed by: "Verification required: confirm every clinical, licensing and achievement statement before use."`;
const providers={
 gemini:async prompt=>{const key=process.env.GEMINI_API_KEY;if(!key)return null;const model=process.env.GEMINI_MODEL||"gemini-2.5-flash";const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${key}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:`${system}\n\n${prompt}`}]}],generationConfig:{temperature:.25,maxOutputTokens:1400}})});if(!r.ok)throw new Error("AI provider request failed");const j=await r.json();return j.candidates?.[0]?.content?.parts?.map(x=>x.text).join("")},
 openai:async prompt=>{const key=process.env.OPENAI_API_KEY;if(!key)return null;const r=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-4.1-mini",temperature:.25,messages:[{role:"system",content:system},{role:"user",content:prompt}]})});if(!r.ok)throw new Error("AI provider request failed");const j=await r.json();return j.choices?.[0]?.message?.content},
 groq:async prompt=>{const key=process.env.GROQ_API_KEY;if(!key)return null;const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.GROQ_MODEL||"llama-3.3-70b-versatile",temperature:.25,messages:[{role:"system",content:system},{role:"user",content:prompt}]})});if(!r.ok)throw new Error("AI provider request failed");const j=await r.json();return j.choices?.[0]?.message?.content},
};
export default async function handler(request,response){if(request.method!=="POST")return response.status(405).json({error:"Method not allowed"});if(rateLimited(request))return response.status(429).json({error:"Too many requests. Please wait one minute."});const {task,profile={},facts="",jobDescription=""}=request.body||{};if(!allowedTasks.has(task))return response.status(400).json({error:"Unsupported assistance type"});if(!facts&&task!=="interview_questions")return response.status(400).json({error:"Add your verified information first"});const prompt=`Task: ${task.replaceAll("_"," ")}\nProfession: ${clean(profile.profession)}\nSpeciality: ${clean(profile.specialty)}\nExperience level: ${clean(profile.experienceLevel)}\nTarget country: ${clean(profile.targetCountry)}\nTarget position: ${clean(profile.targetPosition)}\nLicence status: ${clean(profile.licenceStatus)}\nApplicant verified facts:\n${clean(facts)}\nJob description:\n${clean(jobDescription)}\nWrite an editable draft. Do not claim any unconfirmed competence or metric.`;try{const preferred=process.env.AI_PROVIDER?.toLowerCase();const order=preferred&&providers[preferred]?[preferred,...Object.keys(providers).filter(x=>x!==preferred)]:["gemini","openai","groq"];for(const name of order){const content=await providers[name](prompt);if(content)return response.status(200).json({content,provider:name,requiresVerification:true})}return response.status(503).json({error:"AI assistance is not configured"})}catch{return response.status(502).json({error:"AI assistance is temporarily unavailable"})}}
